### ISSUE TITLE
miThermometer.clearScanResults(); Don't seem to clear anything

### ISSUE THREAD

**Issue by johnostr** [matthias-bs/ATC_MiThermometer#6]
I was thinking that after miThermometer.clearScanResults(); or miThermometer.resetData(); ran the BLE data would clear.  In my case when I run the serial.printf code again (a second time) after the miThermometer.clearScanResults(), just like in the client example, the data is still displaying.  Same data shows again.  

What is the miThermometer.clearScanResults() and miThermometer.resetData() suppose to do?

Other than that the code works great !!

**Comment by matthias-bs** [comment]
miThermometer.resetData() sets the valid flag to false.
miThermometer.clearScanResults() clears the BLE scan data to free allocated memory, but leaves the acquired sensor data untouched.

**Comment by johnostr** [comment]
Many thanks, great to know what they do.
